### ISSUE TITLE
Meta-issue: testrender wish list

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/OpenShadingLanguage#1861]
# Master list of `testrender` feature requests

We will use this issue to collect individual suggestions or feature requests for `testrender`. Some are larger projects that can be later forked off to their own issues, but some are as small as single-day tasks for newcomers.

Please comment/reply on this ticket to request that items be added (or if you're on the TSC or have permissions to edit this description, feel free to do so.

Comment/reply to say "hey, I want to do task X" so that multiple don't independently attempt the same tasks (if it's something where only one can really be accepted); we don't want anybody's work time to be wasted.

## Good First Issues

These are small tasks ideal for newcomers to the project, suitable for Dev Days. They don't really require knowledge of how OSL itself is implemented under the covers, but having written a student project sized path tracer might be helpful (since that's basically what testrender is).

```[tasklist]
- [ ] https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/issues/1976
```

## Intermediate projects

These will require more extensive experience with theory and practice of writing renderer, or perhaps more knowledge of OSL internals, or take longer than first-issue projects.

```[tasklist]
- [ ] Add displacement shader support to testrender
- [ ] Fix uv derivatives in testrender
```

## Advanced projects

Items expected to take an extended effort (say, many weeks), or require a level of expertise of someone who has written a production complexity renderer before.

```[tasklist]
- [ ] Implement support for subsurface scattering
- [ ] Implement support for medium closures (volumetric rendering)
```

**Comment by Arin1604** [comment]
Interested in working on this issue!

**Comment by lgritz** [comment]
@Arin1604 Great! Did you have a specific task or feature you wanted to try?

**Comment by Arin1604** [comment]
@lgritz I would love to start out with creating a test scene based on the USD shaderball!

I'm having hiccups with getting OSL to build on windows. I'll attend the build workshop tomorrow and hopefully will have a successful build going!

**Comment by hridizaroy** [comment]
Hello! I will try to tackle this issue for devdays:
> Fix uv derivatives in testrender

**Comment by lgritz** [comment]
This Issue uses "tasks", which for some reason GitHub is eliminating at the end of the month. They say to convert to subissues, but I can find no way to do that. They have a nice explanatory video showing how to do it, which involves selecting a choice from a pulldown menu, but the "make this task into a sub-issue" choice is NOT in the menu on this ticket. Thanks for the help, GitHub!

I will create a new issue with, hopefully, a way to add proper subissues. @hridizaroy keep an eye open for that, this one will close.

**Comment by vinvinveen** [comment]
Hi can I still work on the USD shaderball?

**Comment by lgritz** [comment]
@vinvinveen Sure!
