### ISSUE TITLE
Meta-issue: osltoy features and fixes

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/OpenShadingLanguage#1862]
# Master list of `osltoy` feature requests

`osltoy` is a small example program loosely inspired by [shadertoy](https://www.shadertoy.com/) -- a Qt application that lets you load or type in an OSL shader, which is then used to evaluate a color for each pixel in the display window of the app, and to interactively change the controls. Unlike the real Shadertoy, it's just meant to be a local app, not a web service. But it's a great way to tinker with OSL shaders, but it hasn't gotten a lot of development love lately.

We will use this issue to collect individual suggestions or feature requests for `osltoy`. Please comment/reply on this ticket to request that items be added (or if you're on the TSC or have permissions to edit this description, feel free to do so.

Comment/reply to say "hey, I want to do task X" so that multiple people don't independently attempt the same tasks (if it's something where only one can really be accepted); we don't want anybody's work time to be wasted.

## Good First Issues

These are small tasks ideal for newcomers to the project, suitable for Dev Days. They don't really require knowledge of how OSL itself is implemented under the covers, but some experience making C++ Qt GUI applications may be helpful, and it probably wouldn't hurt if you've fooled around a bit with the real Shadertoy to get inspiration for some things to add.

```[tasklist]
- [ ] way to set search path for headers?
- [ ] auto-detect output variable -- doesn't need to be Cout if there's only one
- [ ] editor improvement: can we make the tab stops 4 spaces each?
- [ ] watch a shader file on disk, auto reload/recompile when updated
```

## Bigger projects

These might require more extensive experience, planning complex features, or making big design decisions. Or maybe they will be fast? I'm only guessing.

```[tasklist]
- [ ] allow mouse and keyboard input -- somehow they could be fed into inputs to the shader on the next frame or something? Probably it would help to see how ShaderToy did it, for inspiration.
- [ ] allow "memory" -- can we turn any output into an input for the next frame?
```

**Comment by agreen-creator** [comment]
Hello! I am going to be participating in dev days this thursday and friday. I would like to take on this task!
watch a shader file on disk, auto reload/recompile when updated

**Comment by maxwelliverson** [comment]
I too am participating in dev days, and I'm going to be tackling the following task:

> way to set search path for headers?

**Comment by rydrman** [comment]
hello, I'm going to be looking at this one for dev days!

> editor improvement: can we make the tab stops 4 spaces each?

**Comment by silvialpz** [comment]
Hello! I am going to participate in Dev Days :) 

> auto-detect output variable -- doesn't need to be Cout if there's only one


I've been learning some Qt so I'm really excited about this as a good first issue

**Comment by Rafapp** [comment]
Hi! Participating in Dev Days 2025. I have Qt and OSL experience, so I'm looking forward to it! Let me know if you'd like to coordinate @silvialpz

**Comment by lgritz** [comment]
I broke the "output variable" task into a separate subissue: https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/issues/2021

**Comment by Rafapp** [comment]
Just as a heads up: I'll be tackling the file watching process to allow hot reloading for osltoy.

**Comment by Rafapp** [comment]
@lgritz could we make a sub-issue for shader file watching / auto compilation to have discussion there? And just for more context, would we want to do polling with something like `<filesystem>` or do we want to use libraries like [efsw](https://github.com/SpartanJ/efsw) to avoid polling and make things multi-platform?

**Comment by lgritz** [comment]
@Rafapp Sorry, replying to this somehow slipped through the cracks.

I'm not sure I have a strong preference. I will note that since osltoy is already using Qt for the GUI, if there is a file watching functionality somewhere in Qt already (which seems likely), that would probably be preferred over adding a new dependency.

**Comment by Rafapp** [comment]
Right on! I'm working on a prototype with QFileSystemWatcher and trying to get it to work properly, hoping to make a PR soon.
